/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "tertiary-container": "#cac8c7",
        "background": "#121414",
        "surface-dim": "#121414",
        "on-background": "#e2e2e2",
        "on-surface": "#e2e2e2",
        "on-secondary-container": "#b5b5b5",
        "inverse-primary": "#006d35",
        "tertiary-fixed": "#e5e2e1",
        "inverse-surface": "#e2e2e2",
        "on-primary": "#003918",
        "secondary-fixed-dim": "#c6c6c6",
        "outline": "#859585",
        "secondary-fixed": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "on-secondary": "#303030",
        "surface-bright": "#38393a",
        "surface-container-high": "#282a2b",
        "surface-variant": "#333535",
        "on-error": "#690005",
        "primary": "#75ff9e",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-container": "#00612e",
        "outline-variant": "#3b4a3d",
        "on-tertiary": "#313030",
        "on-tertiary-fixed": "#1c1b1b",
        "surface": "#121414",
        "on-primary-fixed-variant": "#005226",
        "inverse-on-surface": "#2f3131",
        "on-tertiary-container": "#545453",
        "on-primary-fixed": "#00210b",
        "surface-container": "#1e2020",
        "on-surface-variant": "#bacbb9",
        "on-secondary-fixed-variant": "#474747",
        "secondary-container": "#474747",
        "surface-container-low": "#1a1c1c",
        "primary-fixed-dim": "#00e475",
        "surface-container-lowest": "#0c0f0f",
        "surface-tint": "#00e475",
        "on-secondary-fixed": "#1b1b1b",
        "surface-container-highest": "#333535",
        "tertiary": "#e7e4e3",
        "primary-container": "#00e676",
        "on-tertiary-fixed-variant": "#474746",
        "error": "#ffb4ab",
        "secondary": "#c6c6c6",
        "primary-fixed": "#62ff96"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "base": "8px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
