/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#00162c',
        'on-primary': '#ffffff',
        'primary-container': '#002b4d',
        'on-primary-container': '#7393bb',
        'primary-fixed': '#d1e4ff',
        'primary-fixed-dim': '#a8c9f3',
        'on-primary-fixed': '#001d36',
        'on-primary-fixed-variant': '#27496c',
        'secondary': '#005faf',
        'on-secondary': '#ffffff',
        'secondary-container': '#479afd',
        'on-secondary-container': '#00315f',
        'secondary-fixed': '#d4e3ff',
        'secondary-fixed-dim': '#a5c8ff',
        'on-secondary-fixed': '#001c3a',
        'on-secondary-fixed-variant': '#004786',
        'tertiary': '#1e1300',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#382600',
        'on-tertiary-container': '#ae8b46',
        'tertiary-fixed': '#ffdea5',
        'tertiary-fixed-dim': '#e9c176',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4201',
        'surface': '#fcf9f8',
        'on-surface': '#1c1b1b',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface-variant': '#43474e',
        'surface-variant': '#e5e2e1',
        'outline': '#73777f',
        'outline-variant': '#c3c6cf',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'inverse-primary': '#a8c9f3',
        'surface-tint': '#406185',
        'charcoal-bg': '#1A1C1E',
        'glass-tint': '#F4F7F9',
        'success-green': '#117B01',
        'subtle-gray': '#777777',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'unit': '8px',
        'gutter-desktop': '32px',
        'gutter-mobile': '16px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
